:- dynamic acc1/7.

acc1('Madera', 'Muebles', 'Pintura', 'Ahora', 'Seco', 'Trapo con alcohol', 'Frotar el trapo con alcohol sobre la mancha las veces que sean hasta que se quite').
acc1('Madera', 'Muebles', 'Pintura', 'Ahora', 'Seco', 'Usar alcohol desnaturalizado', 'Pasa el trapo empapado con alcohol\nsobre la mancha,enjuaga y repite\nlas veces que sea necesario').
acc1('Madera', 'Muebles', 'Pintura', 'Ahora', 'Humedo', 'Empapa un trapo suave y limpio en agua tibia', 'Quita la mancha de pintura con el trapo. \nPuede que necesites enjuagar \ny volver a empapar el trapo varias veces \npara quitar toda la pintura.').
acc1('Madera', 'Muebles', 'Lodo', 'Ahora', 'Humedo', 'Frotar con un paño húmedo ', 'Con algo de trementina y\nrepetir el proceso hasta que\nse quite la mancha').
acc1('Madera', 'Muebles', 'Lodo', 'Ahora', 'Seco', 'Empapa un trapo suave y limpio en agua tibia', 'Quita la mancha de pintura con el trapo. \nPuede que necesites enjuagar \ny volver a empapar el trapo varias veces \npara quitar toda la pintura.').
acc1('Madera', 'Muebles', 'Comida', 'Ahora', 'Seco', 'Comprar un detergente \nde aceite para madera.', 'Con un paño suave, \nfrota la sustancias \nhaciendo movimientos circulares').
acc1('Madera', 'Muebles', 'Comida', 'Ahora', 'Seco', 'Vierte la esencia mineral en un trapo', 'Frótala suavemente en el mueble.\n Limpia los residuos del \nlimpiador con un trapo húmedo.').
acc1('Madera', 'Utencilios de cocina', 'Pintura', 'Ahora', 'Seco', 'Usar alcohol desnaturalizado:', 'Pasa el trapo empapado con alcohol\nsobre la mancha,enjuaga y repite\nlas veces que sea necesario').
acc1('Madera', 'Utencilios de cocina', 'Pintura', 'Ahora', 'Humedo', 'Empapa un trapo suave y limpio en agua tibia', 'Quita la mancha de pintura con el trapo. \nPuede que necesites enjuagar \ny volver a empapar el trapo varias veces \npara quitar toda la pintura.').
acc1('Madera', 'Utencilios de cocina', 'Lodo', 'Ahora', 'Seco', 'Frotar con un paño húmedo ', 'Con algo de trementina y\nrepetir el proceso hasta que\nse quite la mancha').
acc1('Madera', 'Utencilios de cocina', 'Lodo', 'Ahora', 'Humedo', 'Empapa un trapo suave y limpio en agua tibia', 'Quita la mancha de pintura con el trapo. \nPuede que necesites enjuagar \ny volver a empapar el trapo varias veces \npara quitar toda la pintura.').
acc1('Madera', 'Utencilios de cocina', 'Comida', 'Ahora', 'Seco', 'Mezcla el ácido oxálico con agua \npara crear una pasta espesa', 'Aplícalo sobre la mancha con un trapo o\n un pincel desechable.\n Deja que se asiente hasta secar. \nAplícalo varias veces').
acc1('Madera', 'Utencilios de cocina', 'Comida', 'Ahora', 'Humedo', ' Enjuaga con agua \ntibia del grifo. ', 'No la metas en el lavaplatos,\n debido a que este alberga bacterias\n que la madera puede absorber. ').
acc1('Madera', 'Juguetes', 'Pintura', 'Ahora', 'Seco', 'Usar alcohol desnaturalizado:', 'Pasa el trapo empapado con alcohol\nsobre la mancha,enjuaga y repite\nlas veces que sea necesario').
acc1('Madera', 'Juguetes', 'Pintura', 'Ahora', 'Humedo', 'Empapa un trapo suave y limpio en agua tibia', 'Quita la mancha de pintura con el trapo. \nPuede que necesites enjuagar \ny volver a empapar el trapo varias veces \npara quitar toda la pintura.').
acc1('Madera', 'Juguetes', 'Lodo', 'Ahora', 'Seco', 'Empapa un trapo suave y limpio en agua tibia', 'Aplícalo sobre la mancha con un trapo o\n un pincel desechable.\n Deja que se asiente hasta secar. \nAplícalo varias veces').
acc1('Madera', 'Juguetes', 'Lodo', 'Ahora', 'Humedo', 'Frotar con un paño húmedo', 'Con algo de trementina y\nrepetir el proceso hasta que\nse quite la mancha').
acc1('Madera', 'Juguetes', 'Comida', 'Ahora', 'Seco', 'Usa agua tibia. ', ' Restriega con los dedos, \nuna esponja u otra almohadilla \npara limpiar platos. ').
acc1('Madera', 'Juguetes', 'Comida', 'Ahora', 'Humedo', 'Mezcla el ácido oxálico con agua \npara crear una pasta espesa', 'Aplícalo sobre la mancha con un trapo o\n un pincel desechable.\n Deja que se asiente hasta secar. \nAplícalo varias veces').
acc1('Metal', 'Muebles', 'Pintura', 'Ahora', 'Seco', 'Aplica alcohol isopropílico', 'En un paño suave \ny frótalo con cuidado sobre la superficie ').
acc1('Metal', 'Muebles', 'Pintura', 'Ahora', 'Humedo', 'Utiliza el paño húmedo para absorber la pintura\n y limpiarla', 'Vierte un poco de alcohol en un paño.\nPon el paño sobre la pintura por diez minutos. \nLuego, limpia con un paño húmedo.').
acc1('Metal', 'Muebles', 'Lodo', 'Ahora', 'Seco', 'Empapa un trapo en agua tibia', 'Puede que necesites enjuagar \ny volver a empapar el trapo varias veces .').
acc1('Metal', 'Muebles', 'Lodo', 'Ahora', 'Humedo', 'Frotar con un paño húmedo ', 'Con algo de trementina y\nrepetir el proceso hasta que\nse quite la mancha').
acc1('Metal', 'Muebles', 'Comida', 'Ahora', 'Seco', 'Espolvorea bicarbonato de sodio.', ' Frota el bicarbonato de sodio\n con una esponja o un paño seco.').
acc1('Metal', 'Muebles', 'Comida', 'Ahora', 'Humedo', 'Llena 2/3 de una cubeta con agua tibia o caliente.', ' Si el objeto es pequeño,\n puedes aplicar agua y jabón\n directamente en una toalla. ').
acc1('Metal', 'Utencilios de cocina', 'Pintura', 'Ahora', 'Seco', 'Aplica alcohol isopropílico', ' En un paño suave \ny frótalo con cuidado sobre la superficie ').
acc1('Metal', 'Utencilios de cocina', 'Pintura', 'Ahora', 'Humedo', 'Utiliza el paño húmero para absorber la pintura\n y limpiarla', 'Vierte un poco de alcohol en un paño.\nPon el paño sobre la pintura por diez minutos. \nLuego, limpia con un paño húmedo.').
acc1('Madera', 'Utencilios de cocina', 'Lodo', 'Ahora', 'Seco', 'Frotar con un paño húmedo ', 'Con algo de trementina y\nrepetir el proceso hasta que\nse quite la mancha').
acc1('Metal', 'Utencilios de cocina', 'Lodo', 'Ahora', 'Humedo', 'Empapa un trapo en agua tibia', 'uede que necesites enjuagar \ny volver a empapar el trapo varias veces .').
acc1('Metal', 'Utencilios de cocina', 'Comida', 'Ahora', 'Seco', 'Espolvorea bicarbonato de sodio.', 'Frota el bicarbonato de sodio\n con una esponja o un paño seco.').
acc1('Metal', 'Utencilios de cocina', 'Comida', 'Ahora', 'Humedo', 'Llena 2/3 de una cubeta con agua tibia o caliente.', ' Si el objeto es pequeño,\n puedes aplicar agua y jabón\n directamente en una toalla.').
acc1('Metal', 'Juguetes', 'Pintura', 'Ahora', 'Seco', 'Aploca alcohol isopropílico', 'En un paño suave \ny frótalo con cuidado sobre la superficie ').
acc1('Metal', 'Juguetes', 'Pintura', 'Ahora', 'Humedo', 'Utiliza el paño húmero para absorber la pintura\n y limpiarla', 'Vierte un poco de alcohol en un paño.\nPon el paño sobre la pintura por diez minutos. \nLuego, limpia con un paño húmedo.').
acc1('Metal', 'Juguetes', 'Lodo', 'Ahora', 'Seco', 'Empapa un trapo en agua tibia', 'Puede que necesites enjuagar \ny volver a empapar el trapo varias veces .').
acc1('Metal', 'Juguetes', 'Lodo', 'Ahora', 'Humedo', 'Frotar con un paño húmedo ', 'Con algo de trementina y\nrepetir el proceso hasta que\nse quite la mancha').
acc1('Metal', 'Juguetes', 'Comida', 'Ahora', 'Seco', 'Espolvorea bicarbonato de sodio.', 'Frota el bicarbonato de sodio\n con una esponja o un paño seco.').
acc1('Metal', 'Juguetes', 'Comida', 'Ahora', 'Humedo', 'Llena 2/3 de una cubeta con agua tibia o caliente.', 'Si el objeto es pequeño,\n puedes aplicar agua y jabón\n directamente en una toalla. ').
acc1('Plastico', 'Muebles', 'Pintura', 'Ahora', 'Seco', 'Usar alcohol desnaturalizado:', 'Pasa el trapo empapado con alcohol\nsobre la mancha,enjuaga y repite\nlas veces que sea necesario').
acc1('Madera', 'Muebles', 'Pintura', 'Ahora', 'Humedo', 'Empapa un trapo suave y limpio en agua tibia', 'Quita la mancha de pintura con el trapo. \nPuede que necesites enjuagar \ny volver a empapar el trapo varias veces \npara quitar toda la pintura.').
acc1('Plastico', 'Muebles', 'Lodo', 'Ahora', 'Seco', 'Empapa un trapo suave y limpio en agua tibia', 'Puede que necesites enjuagar \ny volver a empapar el trapo varias veces \npara quitar toda la pintura.').
acc1('Plastico', 'Muebles', 'Lodo', 'Ahora', 'Humedo', 'Frotar con un paño húmedo ', 'Con algo de trementina y\nrepetir el proceso hasta que\nse quite la mancha').
acc1('Plastico', 'Muebles', 'Comida', 'Ahora', 'Seco', 'Vierte la esencia mineral en un trapo', 'Frótala suavemente en el mueble.\n Limpia los residuos del \nlimpiador con un trapo húmedo.').
acc1('Plastico', 'Muebles', 'Comida', 'Ahora', 'Humedo', 'Comprar un detergente ', 'Con un paño suave, \nfrota la sustancias \nhaciendo movimientos circulares').
acc1('Plastico', 'Utencilios de cocina', 'Pintura', 'Ahora', 'Seco', 'Usar alcohol desnaturalizado:', 'Pasa el trapo empapado con alcohol\nsobre la mancha,enjuaga y repite\nlas veces que sea necesario').
acc1('Plastico', 'Utencilios de cocina', 'Pintura', 'Ahora', 'Humedo', 'Empapa un trapo suave y limpio en agua tibia', 'Quita la mancha de pintura con el trapo. \nPuede que necesites enjuagar \ny volver a empapar el trapo varias veces \npara quitar toda la pintura.').
acc1('Plastico', 'Utencilios de cocina', 'Lodo', 'Ahora', 'Seco', 'Mezcla el ácido oxálico con agua \npara crear una pasta espesa', ' Aplícalo sobre la mancha con un trapo o\n un pincel desechable.\n Deja que se asiente hasta secar. \nAplícalo varias veces').
acc1('Plastico', 'Utencilios de cocina', 'Lodo', 'Ahora', 'Humedo', 'Frotar con un paño húmedo ', 'Con algo de trementina y\nrepetir el proceso hasta que\nse quite la mancha').
acc1('Plastico', 'Utencilios de cocina', 'Comida', 'Ahora', 'Seco', 'Comprar un detergente ', 'Con un paño suave, \nfrota la sustancias \nhaciendo movimientos circulares').
acc1('Plastico', 'Utencilios de cocina', 'Comida', 'Ahora', 'Humedo', 'Vierte la esencia mineral en un trapo ', 'Frótala suavemente en el mueble.\n Limpia los residuos del \nlimpiador con un trapo húmedo.').
acc1('Plastico', 'Juguetes', 'Pintura', 'Ahora', 'Seco', 'Usar alcohol desnaturalizado:', 'Pasa el trapo empapado con alcohol\nsobre la mancha,enjuaga y repite\nlas veces que sea necesario').
acc1('Plastico', 'Juguetes', 'Pintura', 'Ahora', 'Humedo', 'Empapa un trapo suave y limpio en agua tibia', 'Quita la mancha de pintura con el trapo. \nPuede que necesites enjuagar \ny volver a empapar el trapo varias veces \npara quitar toda la pintura.').
acc1('Plastico', 'Juguetes', 'Lodo', 'Ahora', 'Seco', 'Mezcla el ácido oxálico con agua \npara crear una pasta espesa', 'Aplícalo sobre la mancha con un trapo o\n un pincel desechable.\n Deja que se asiente hasta secar. \nAplícalo varias veces').
acc1('Plastico', 'Juguetes', 'Lodo', 'Ahora', 'Humedo', 'Frotar con un paño húmedo ', 'Con algo de trementina y\nrepetir el proceso hasta que\nse quite la mancha').
acc1('Plastico', 'Juguetes', 'Comida', 'Ahora', 'Seco', 'Usa agua tibia.', 'Restriega con los dedos, \nuna esponja u otra almohadilla \npara limpiar platos. ').
acc1('Plastico', 'Juguetes', 'Comida', 'Ahora', 'Humedo', 'Mezcla el ácido oxálico con agua \npara crear una pasta espesa', 'Aplícalo sobre la mancha con un trapo o\n un pincel desechable.\n Deja que se asiente hasta secar. \nAplícalo varias veces').
acc1('Madera', 'Muebles', 'Lodo', '30 min', 'Humedo', 'Frotar con paño húmedo', 'Frotar con un paño húmedo con algo de trmenlina y repetir el proceso hasta que se quite la mancha').
acc1('Madera', 'Muebles', 'Pintura', '1 Hora', 'Seco', 'Alcohol desnaturalizado', 'Pasa el trapo empapado con alcohol sobre la mancha enjuaga y repite las veces que sea necesario').
acc1('Madera', 'Muebles', 'Comida', '1 Hora', 'Seco', 'Comprar detergente', 'Compre un detergente de aceite para madera, frota la sustancia haciendo movimientos circulares').
acc1('Madera', 'Muebles', 'Pintura', '30 min', 'Humedo', 'Empapa un trapo', 'Quita la mancha de pintura con el trapo, puede que necesites enjuagar y volver a empapar el trapo varias veces para quitar la pintura').
acc1('Madera', 'Muebles', 'Lodo', '1 Hora', 'Seco', 'Mezcla el ácido oxálico con agua', 'Crea una pasta espesa. Aplícalo sobre la mancha con un trapo o pincel desechable, deje que se asiente hasta secar, aplícalo varias veces').
acc1('Madera', 'Utencilios de cocina', 'Pintura', '1 Hora', 'Seco', 'Alcohol desnaturalizado', 'Pasa el trapo empapado con alcohol\nsobre la mancha,enjuaga y repite\nlas veces que sea necesario').
acc1('Madera', 'Utencilios de cocina', 'Lodo', '30 min', 'Humedo', 'Mezcla el ácido oxálico con agua', 'Crea una pasta espesa\n Aplícalo sobre la mancha con un trapo o\n un pincel desechable.\n Deja que se asiente hasta secar. \nAplícalo varias veces').
acc1('Madera', 'Utencilios de cocina', 'Comida', '1 Hora', 'Humedo', 'Enjuaga con agua \ntibia del grifo', 'No la metas en el lavaplatos,\n debido a que este alberga bacterias\n que la madera puede absorber. ').
acc1('Madera', 'Juguetes', 'Pintura', '30 min', 'Humedo', 'Empapa un trapo suave y limpio en agua tibia', 'Quita la mancha de pintura con el trapo. \nPuede que necesites enjuagar \ny volver a empapar el trapo varias veces \npara quitar toda la pintura.').
acc1('Madera', 'Juguetes', 'Lodo', '1 Hora', 'Seco', 'Mezcla el ácido oxálico con agua', ' Aplícalo sobre la mancha con un trapo o\n un pincel desechable.\n Deja que se asiente hasta secar. \nAplícalo varias veces').
acc1('Madera', 'Juguetes', 'Comida', '30 min', 'Humedo', 'Usa agua tibia. ', 'Restriega con los dedos, \nuna esponja u otra almohadilla \npara limpiar platos.').
acc1('Madera', 'Juguetes', 'Comida', '1 Hora', 'Seco', 'Mezcla el ácido oxálico con agua', ' Aplícalo sobre la mancha con un trapo o\n un pincel desechable.\n Deja que se asiente hasta secar. \nAplícalo varias veces').
acc1('Madera', 'Juguetes', 'Pintura', '30 min', 'Seco', 'Alcohol desnaturalizado', 'Pasa el trapo empapado con alcohol\nsobre la mancha,enjuaga y repite\nlas veces que sea necesario').
acc1('Madera', 'Juguetes', 'Comida', '30 min', 'Humedo', 'Usa agua tibia', 'Restriega con los dedos, \nuna esponja u otra almohadilla \npara limpiar platos.').
acc1('Metal', 'Muebles', 'Pintura', '30 min', 'Seco', 'Alcohol isopropílico', 'Aplica alcohol isopropílico en un paño suave \ny frótalo con cuidado sobre la superficie ').
acc1('Metal', 'Muebles', 'Pintura', '1 Hora', 'Humedo', 'Paño húmero para absorber la pintura', 'Utiliza el paño húmero para absorber la pintura y limpiarla, en vez de esparcirla vierte un poco de alcohol en un paño.\nPon el paño sobre la pintura por diez minutos. \nLuego, limpia con un paño húmedo.').
acc1('Metal', 'Muebles', 'Lodo', '30 min', 'Seco', 'Empapa un trapo en agua tibia', 'Puede que necesites enjuagar \ny volver a empapar el trapo varias veces .').
acc1('Metal', 'Utencilios de cocina', 'Comida', '1 Hora', 'Seco', 'Alcohol isopropílico en un paño suave', 'Aplica alcohol isopropílico en un paño suave \ny frótalo con cuidado sobre la superficie ').
acc1('Metal', 'Juguetes', 'Pintura', '30 min', 'Humedo', 'Paño húmero para absorber la pintura', 'Utiliza el paño húmero para absorber la pintura\n y limpiarla, en vez de esparcirla\nvierte un poco de alcohol en un paño.\nPon el paño sobre la pintura por diez minutos.').
acc1('Metal', 'Utencilios de cocina', 'Pintura', '30 min', 'Humedo', 'Paño humedo', 'Utiliza el paño húmero para absorber la pintura\n y limpiarla, en vez de esparcirla\nvierte un poco de alcohol en un paño.\nPon el paño sobre la pintura por diez minutos.').
acc1('Metal', 'Muebles', 'Pintura', '1 Hora', 'Seco', 'Alcohol isopropílico', 'Aplica alcohol isopropílico en un paño suave \ny frótalo con cuidado sobre la superficie ').
acc1('Metal', 'Juguetes', 'Comida', '1 Hora', 'Seco', 'Bicarbonato de sodio', 'Asegúrate de que la superficie este seca\n y espolvorea bicarbonato de sodio.\n frota el bicarbonato de sodio\n con una esponja o un paño seco.').
acc1('Metal', 'Utencilios de cocina', 'Comida', '30 min', 'Humedo', 'Bicarbonato de sodio', 'Asegúrate de que la superficie este seca\n y espolvorea bicarbonato de sodio.\n frota el bicarbonato de sodio\n con una esponja o un paño seco.').
acc1('Metal', 'Juguetes', 'Lodo', '1 Hora', 'Seco', 'Trapo y Agua Tibia', 'segúrate de que la superficie este seca\n y espolvorea bicarbonato de sodio.\n frota el bicarbonato de sodio\n con una esponja o un paño seco.').
acc1('Metal', 'Juguetes', 'Lodo', '1 Hora', 'Humedo', 'Paño y Trementina', 'Frotar con un paño húmedo \ncon algo de trementina y\nrepetir el proceso hasta que\nse quite la mancha').
acc1('Metal', 'Juguetes', 'Comida', '30 min', 'Seco', 'Bicarbonato de sodio, Esponja o Trapo Humedo', 'Asegúrate de que la superficie este seca\n y espolvorea bicarbonato de sodio.\n frota el bicarbonato de sodio\n con una esponja o un paño seco.').
acc1('Madera', 'Juguetes', 'Comida', '30 min', 'Humedo', 'Agua Jabón', 'Llena 2/3 de una cubeta con agua tibia o caliente.\n Si el objeto es pequeño,\n puedes aplicar agua y jabón\n directamente en una toalla. ').
acc1('Plastico', 'Muebles', 'Lodo', '30 min', 'Seco', 'Bicarbonato de sodio', 'Usa un cepillo de cerdas, si hay \npartes con mucho lodo seco use\n un poco\nde bicarbonato de sodio, \nesta permitira eliminar la suciedad, tete no frotarlo\nmuy fuerte para no  dañar').
acc1('Plastico', 'Muebles', 'Pintura', '1 Hora', 'Seco', 'Agua con cloro', 'Frotá con una esponja vigorosamente, \naunque con cuidado de no rayar la superficie').
acc1('Plastico', 'Muebles', 'Comida', '30 min', 'Humedo', 'Amoniaco diluido en agua', 'En caso de que estén muy sucios, pegajosos o grasientos,\n te recomendamos limpiar los muebles con amoniaco diluido en agua, \nya que será capaz de eliminar fácilmente la suciedad más incrustada.\n También podrás agregar a la mezcla un chorro de jabón para\nlavar los platos y también te sugerimos leer cómo\n usar el amoniaco para limpiar para que no te queden dudas.').
acc1('Plastico', 'Muebles', 'Lodo', '1 Hora', 'Seco', 'Bicarbonato de sodio', 'Usa un cepillo de cerdas, si hay \npartes con mucho lodo seco use\n un poco\nde bicarbonato de sodio, \nesta permitira eliminar la suciedad, tete no frotarlo\nmuy fuerte para no  dañar').
acc1('Plastico', 'Muebles', 'Lodo', '30 min', 'Humedo', 'Bicarbonato de Sodio', 'Usa un cepillo de cerdas, si hay \npartes con mucho lodo seco use\n un poco\nde bicarbonato de sodio, \nesta permitira eliminar la suciedad, tete no frotarlo\nmuy fuerte para no  dañar').
acc1('Plastico', 'Utencilios de cocina', 'Comida', '30 min', 'Seco', 'Bicarbonato', 'Primero se humedece un trapo \nen agua y se pasa luego \npor un poco de bicarbonato.\n Después se procede a \nfrotarlo sobre las\n manchas de té o café que\n hayan quedado en la vajilla.').
acc1('Plastico', 'Utencilios de cocina', 'Comida', '1 Hora', 'Humedo', 'Agua y Trapo', 'Primero se humedece un trapo \nen agua y se pasa luego \npor un poco de bicarbonato.\n Después se procede a \nfrotarlo sobre las\n manchas de té o café que\n hayan quedado en la vajilla.').
acc1('Plastico', 'Juguetes', 'Comida', '1 Hora', 'Seco', 'Mezcla de bicarbonato de sodio. Agua', 'Limpia el plástico con la mezcla de bicarbonato de sodio.\nAplica esta pasta a una superficie de plástico con un paño o esponja limpios. \nRestriega. Restriega el plástico con la mezcla de\n bicarbonato de sodio para eliminar la suciedad. \nEnjuaga el plástico con agua. ').
acc1('Plastico', 'Juguetes', 'Comida', '30 min', 'Seco', 'Mezcla de Bicarbonato de sodio y agua', 'Limpia el plástico con la mezcla de bicarbonato de sodio.\nAplica esta pasta a una superficie de plástico con un paño o esponja limpios. \nRestriega. Restriega el plástico con la mezcla de\n bicarbonato de sodio para eliminar la suciedad. \nEnjuaga el plástico con agua. ').
acc1('Plastico', 'Juguetes', 'Pintura', '1 Hora', 'Seco', 'Cloruro de polivinilo', 'El PVC (Cloruro de polivinilo) es \nun polímero termoplástico bastante popular. \n\nuna gran variedad de productos, \nlo que lo hace uno de los elementos \nmás valiosos en la industria química.').
acc1('Plastico', 'Utencilios de cocina', 'Comida', '1 Hora', 'Seco', 'Use varita magica', 'Agitela 3 veces').

